title: Code-J
logo: /assets/logos/banner2.png
description: >-
  I’m Ji Yong-Hyeon, pursuing cryptology where mathematics meets computer science — turning theory into secure, practical systems through hands-on research and projects.

# For a user/organization site (username.github.io):
baseurl: "" # no leading slash
url: "https://hacker-code-j.github.io"

# For a project site (e.g., github.com/username/my-github-blog):
# baseurl: "/my-github-blog" # repo name prefixed with a slash
# url: "https://username.github.io"

# Build settings
theme: minima

minima:
  skin: auto
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/hacker-code-j/"
    # - title: Youtube
    #   icon: youtube
    #   url: "https://www.youtube.com/@hacker-code-j"

markdown: kramdown 

#   silence_deprecations: [import, global-builtin, color-functions]
sass:
  style: compressed
  load_paths:
    - _sass
    - assets
defaults:
  - scope:
      path: "assets/main.scss"
    values:
      layout: null

author:
  name: Ji, Yong-Hyeon
  email: "hacker3740@gmail.com"

header_pages:
  - preprints.markdown
  - projects.markdown
  - articles.markdown
  - codes.markdown
  - talks.markdown
  - life.markdown

# Exclude from processing.
exclude:
  - .bundle
  - .git/
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/

# Collections
collections:
  preprints:
    output: true
    sort_by: year
  publications:
    sort_by: year
  projects:
    output: true
    permalink: /:collection/:name
  theses:
    sort_by: year
  articles:
    output: true
    permalink: /articles/:title/
  notes:
    output: true
    permalink: /:collection/:name
  news:
    sort_by: date
    output: true
    permalink: /:collection/:year-:month-:day/:title
  codes:
    output: true
    permalink: /codes/:name/
  talks:
    output: true
    permalink: /talks/:title/
  life:
    output: true
    permalink: /life/:title/
# collections:
# research:
# output: true
# permalink: /research/:title/
# projects:
# output: true
# permalink: /projects/:title/
# notes:
# output: true
# permalink: /notes/:title/
# tutorials:
# output: true
# permalink: /tutorials/:title/

github:
  user: your-github-username
  repo: your-repo-name
  branch: main

defaults:
  - scope: { path: "", type: "articles" }
    values: { layout: page }
  - scope: { path: "", type: "projects" }
    values: { layout: page, permalink: /projects/:name/ }
  - scope: { path: "", type: "publications" }
    values: { layout: page, permalink: /publications/:name/}


# # Apply a default top-level category of "professional"
# defaults:
#   - scope:
#     path: ""
#     values:
#     layout: post
#     categories: [professional]
#   - scope:
#     path: "_research"
#     type: research
#     values:
#     categories: [professional, research]
#   - scope:
#     path: "_projects"
#     type: projects
#     values:
#     categories: [professional, projects]
#   - scope:
#     path: "_notes"
#     type: notes
#     values:
#     categories: [professional, notes]
#   - scope:
#     path: "_tutorials"
#     type: tutorials
#     values:
#     categories: [professional, tutorials]
#   - scope:
#     path: "_talks"
#     type: talks
#     values:
#     categories: [professional, talks]

# Markdown + plugins (optional but commonly used)
# markdown: kramdown
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
