title: Your Site Title
logo: /assets/logos/logo1.png
description: >-
  A short description of your site goes here. It can span multiple lines
  thanks to the folded block scalar.

# For a user/organization site (username.github.io):
baseurl: "" # no leading slash
url: "https://username.github.io"

# For a project site (e.g., github.com/username/my-github-blog):
# baseurl: "/my-github-blog" # repo name prefixed with a slash
# url: "https://username.github.io"

# Build settings
theme: minima

minima:
  skin: auto
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/username/"
    - title: Gitlab
      icon: gitlab
      url: "https://gitlab.com/username/"

sass:
  silence_deprecations: [import, global-builtin, color-functions]

author:
  name: Your Name or Team Name
  email: "you@example.com"

header_pages:
  - news.markdown
  - people.markdown
  - tools.markdown
  - projects.markdown
  - publications.markdown
  - support.markdown

# Exclude from processing.
exclude:
  - .bundle
  - .git/
  - .gitignore
  - .gitlab-ci.yml
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _site/
  - _funding/sample.markdown
  - _news/2022-03-29-sample.markdown

# Collections
collections:
  people:
    sort_by: name
  former_members:
    sort_by: name
  tools:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name
  publications:
    sort_by: year
  theses:
    sort_by: year
  preprints:
    sort_by: year
  funding:
  supporters:
    sort_by: name
  institutions:
    sort_by: name
  news:
    sort_by: date
    output: true
    permalink: /:collection/:year-:month-:day/:title

# Markdown + plugins (optional but commonly used)
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
