name: Build & Deploy

permissions:
  contents: write      # allow pushing to gh-pages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Build site
        run: |
          bundle exec jekyll build --destination public
          touch public/.nojekyll   # prevent any further Jekyll run

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
